brokerClusterName=linklifeRmqItCluster
brokerName=linklife-rmq-it-timeout-broker
brokerId=0
brokerRole=ASYNC_MASTER
flushDiskType=SYNC_FLUSH
autoCreateTopicEnable=false
timerWheelEnable=true
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
