/** 与 docs/evidence 对应的工程验证结果。 */
export const engineeringEvidence = {
  note: '服务端与 JMeter 压测端分离，所有数字均来自双机正式测试。',
  tests: {
    count: 1011,
    failures: 0,
    errors: 0,
    skipped: 5,
  },
  officialBenchmarkRuns: 36,
  independentDatabases: 4,
  springProcesses: 5,
  transactionFlow: ['Lua 原子准入', 'Redis Stream', 'Consumer Group / PEL', 'MySQL 事务'],
  reliabilitySides: ['重试', 'DLQ', '补偿', 'Outbox', '超时关单'],
  cache: {
    title: '双机 500 并发',
    qps: '≈17.4K',
    p95: '36 ms',
    p99: '45 ms',
    before: '≈0.788',
    after: '≈0.000092',
    reduction: 'Redis GET 调用量降低约 99.98%',
    note: 'Caffeine 关闭与开启的三轮中位数对比',
  },
  seckill1000: {
    persistedOrders: 1000,
    distinctUsers: 1000,
    duplicate: 0,
    oversell: 0,
    httpErrors: 0,
    p95: '≈40 ms',
    p99: '≈44 ms',
    pel: 0,
    dlq: 0,
    note: '1000 个不同用户，连续 3 轮正确性验证通过',
  },
  reliability: [
    {
      title: 'Gateway 热点限流',
      result: '通过',
      detail: '精确 429 限流且不产生订单副作用',
    },
    {
      title: 'Identity 服务故障',
      result: '通过',
      detail: '展示接口降级、关键调用阻断，恢复后自动复原',
    },
    {
      title: 'Redis 重启',
      result: '通过',
      detail: 'AOF 恢复会话 / Stream / PEL 状态',
    },
    {
      title: '秒杀期间 MySQL 故障',
      result: '通过',
      detail: '消息保留在 PEL；恢复后同一订单完成落库',
    },
  ],
  mysqlRecoveryNote: '本地恢复收敛观测：8.45 s',
}
